name: "🚀 publish"

on:
  push:
    branches:
      - master

jobs:
  release:
    name: "🚀 publish"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.1.1
      - name: node
        uses: actions/setup-node@v1.4.2
        with:
          node-version: 16
          registery-url: https://registry.npmjs.org
      - name: 🚀 publish
        run: npm publish --access public
        working-directory: packages/cli
        env:
          NODE_AITH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}